export const SPEC_MAPPING = {
  Forklift: [
    { label: 'Nama Operator', key: 'nama_operator' },
    { label: 'Pabrik Pembuat', key: 'pabrik_pembuat' },
    { label: 'Merk', key: 'merk_type' },
    { label: 'Tempat & Tahun Pembuatan', key: 'tempat_tahun_pembuatan' },
    { label: 'No. Series / No. Unit', key: 'no_series_no_unit' },
    { label: 'Kapasitas', key: 'kapasitas' },
    { label: 'Digunakan untuk', key: 'digunakan_untuk' },
    { label: 'Sertifikat Operator', key: 'sertifikat_operator' },
    { label: 'Data Riwayat Pesawat', key: 'data_riwayat_pesawat' },
  ],
  'Conveyor Machine': [
    { label: 'Nama Operator', key: 'nama_operator' },
    { label: 'Pabrik Pembuat', key: 'pabrik_pembuat' },
    { label: 'Merk', key: 'merk_type' },
    { label: 'Tempat & Tahun Pembuatan', key: 'tempat_tahun_pembuatan' },
    { label: 'No. Series / No. Unit', key: 'no_series_no_unit' },
    { label: 'Kapasitas', key: 'kapasitas' },
    { label: 'Digunakan untuk', key: 'digunakan_untuk' },
    { label: 'Sertifikat Operator', key: 'sertifikat_operator' },
    { label: 'Data Riwayat Pesawat', key: 'data_riwayat_pesawat' },
  ],
  Gondola: [
    { label: 'Pengurus / Penanggungjawab', key: 'pengurus_penanggungjawab' },
    { label: 'Jenis Pesawat', key: 'jenis_pesawat' },
    { label: 'Merk / Model', key: 'merk_model' },
    { label: 'No. Seri', key: 'no_seri' },
    { label: 'Perusahaan Pembuat', key: 'perusahaan_pembuat' },
    { label: 'Perusahaan Pemasang', key: 'perusahaan_pemasang' },
    { label: 'Lokasi / Tahun Pembuatan', key: 'lokasi_tahun_pembuatan' },
    { label: 'Kapasitas', key: 'kapasitas' },
    { label: 'Digunakan Untuk', key: 'digunakan_untuk' },
    { label: 'Nomor Izin Pemakaian / Penerbit', key: 'no_izin_penerbit' },
    { label: 'Kecepatan Angkat', key: 'kecepatan_angkat' },
    { label: 'Data Riwayat Pesawat', key: 'data_riwayat_pesawat' },
  ],
  'Lift Barang': [
    { label: 'Nama Operator', key: 'nama_operator' },
    { label: 'Pabrik Pembuat', key: 'pabrik_pembuat' },
    { label: 'Merk', key: 'merk_type' },
    { label: 'Tempat & Tahun Pembuatan', key: 'tempat_tahun_pembuatan' },
    { label: 'No. Series / No. Unit', key: 'no_series_no_unit' },
    { label: 'Kapasitas', key: 'kapasitas' },
    { label: 'Digunakan untuk', key: 'digunakan_untuk' },
    { label: 'Sertifikat Operator', key: 'sertifikat_operator' },
    { label: 'Data Riwayat Pesawat', key: 'data_riwayat_pesawat' },
  ],
  'Overhead Travelling Crane': [
    { label: 'Nama Operator', key: 'nama_operator' },
    { label: 'Pabrik Pembuat', key: 'pabrik_pembuat' },
    { label: 'Merk', key: 'merk_type' },
    { label: 'Tempat & Tahun Pembuatan', key: 'tempat_tahun_pembuatan' },
    { label: 'No. Series / No. Unit', key: 'no_series_no_unit' },
    { label: 'Kapasitas', key: 'kapasitas' },
    { label: 'Digunakan untuk', key: 'digunakan_untuk' },
    { label: 'Sertifikat Operator', key: 'sertifikat_operator' },
    { label: 'Data Riwayat Pesawat', key: 'data_riwayat_pesawat' },
  ],
  'Two Post Lift': [
    { label: 'Pengurus / Penanggungjawab', key: 'pengurus_penanggungjawab' },
    { label: 'Jenis Pesawat', key: 'jenis_pesawat' },
    { label: 'Merk / Model', key: 'merk_model' },
    { label: 'No. Seri', key: 'no_seri' },
    {
      label: 'Perusahaan Pembuat / Pemasang',
      key: 'perusahaan_pembuat_pemasang',
    },
    { label: 'Lokasi / Tahun Pembuatan', key: 'lokasi_tahun_pembuatan' },
    { label: 'Kapasitas', key: 'kapasitas' },
    { label: 'Digunakan Untuk', key: 'digunakan_untuk' },
    { label: 'Tinggi Angkat', key: 'tinggi_angkat' },
    { label: 'Nomor Izin Pemakaian / Penerbit', key: 'no_izin_penerbit' },
    { label: 'Kecepatan Angkat', key: 'kecepatan_angkat' },
    { label: 'Data Riwayat Pesawat', key: 'data_riwayat_pesawat' },
  ],
  'Wheel Loader': [
    { label: 'Pengurus / Penanggungjawab', key: 'pengurus_penanggungjawab' },
    { label: 'Nama Operator', key: 'nama_operator' },
    { label: 'Pabrik Pembuat', key: 'pabrik_pembuat' },
    { label: 'Merk', key: 'merk_type' },
    { label: 'Tempat & Tahun Pembuatan', key: 'tempat_tahun_pembuatan' },
    { label: 'No. Series / No. Unit', key: 'no_series_no_unit' },
    { label: 'Kapasitas', key: 'kapasitas' },
    { label: 'Digunakan untuk', key: 'digunakan_untuk' },
    { label: 'Sertifikat Operator', key: 'sertifikat_operator' },
    { label: 'Data Riwayat Pesawat', key: 'data_riwayat_pesawat' },
  ],
  'Motor Diesel': [
    { label: 'Pengurus / Penanggungjawab', key: 'pengurus_penanggungjawab' },
    { label: 'Nama Operator', key: 'nama_operator' },
    { label: 'Pabrik Pembuat', key: 'pabrik_pembuat' },
    { label: 'Merk', key: 'merk_type' },
    { label: 'Tempat & Tahun Pembuatan', key: 'tempat_tahun_pembuatan' },
    { label: 'No. Series / No. Unit', key: 'no_series_no_unit' },
    { label: 'Kapasitas', key: 'kapasitas' },
    { label: 'Digunakan untuk', key: 'digunakan_untuk' },
    { label: 'Klasifikasi', key: 'klasifikasi' },
    { label: 'Data Riwayat', key: 'data_riwayat' },
  ],
  'Instalasi Alarm Automatik': [
    { label: 'Penggunaan Bangunan', key: 'penggunaan_bangunan' },
    { label: 'Nama Pemilik / Pimpinan', key: 'nama_pemilik_pimpinan' },
    { label: 'Instalatir', key: 'instalatir' },
    { label: 'Alamat Instalatir', key: 'alamat_instalatir' },
    { label: 'Data Riwayat', key: 'data_riwayat' },
  ],
  'Instalasi Hydrant': [
    { label: 'Penggunaan Bangunan', key: 'penggunaan_bangunan' },
    { label: 'Nama Pemilik / Pimpinan', key: 'nama_pemilik_pimpinan' },
    { label: 'Instalatir', key: 'instalatir' },
    { label: 'Alamat Instalatir', key: 'alamat_instalatir' },
    { label: 'Data Riwayat', key: 'data_riwayat' },
  ],
  'Instalasi Listrik': [
    { label: 'Instalatir Pemasang', key: 'instalatir_pemasang' },
    { label: 'Surat Penunjukan', key: 'surat_penunjukan' },
    { label: 'As Built Drawing', key: 'as_built_drawing' },
    { label: 'Data Riwayat', key: 'data_riwayat' },
  ],
};
